[package]
name = "cli"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
cryimg_core = { version = "0.1.0", path = "../cryimg_core" }
image = "0.25.6"
rand_chacha = "0.9.0"
